### ISSUE TITLE
make available on maven central 

### ISSUE THREAD

**Issue by nmn** [Enigmatis/graphql-java-annotations#10]
can you please make this available in a public repo such as Maven central?

**Comment by yrashk** [comment]
@nmn I will do this soon. In the meantime, you can use jcenter:

``` groovy
repositories {
    jcenter()
}

dependencies {
  compile "graphql-java-annotations:graphql-java-annotations:${graphQLJavaAnnotationsVersion}"
}
```

Are there any issues using jcenter on your end?

**Comment by nmn** [comment]
@yrashk There are some restrictions at work such that It's much easier to get packages from Maven Central approved.

Also, I've working with the library the last couple of days, and while I figured out many of my problems
1. I can't seem to figure out the correct way to define the top level Query and Mutation fields correctly.
   Right now I have to set a `@GraphQLDataFetcher` annotation on every method.
2. Can you help out with how to declare argument types such as Lists?

A small example with the project would be great, but if not, if you could give me answers to those problems I'd be happy to create an example project, and add some docs in a PR.

**Comment by yrashk** [comment]
Gotcha. Will follow through with publishing to Maven Central in the coming days.

**Comment by yrashk** [comment]
As for your 1st question, perhaps this example can be useful: https://github.com/graphql-java/graphql-java-servlet/blob/master/src/main/java/graphql/servlet/GraphQLServlet.java 

Please let me know if this helps or if you still have a problem!

As for your 2nd question, can you formulate this question more specifically? (Also, ideally, in a separate ticket to avoid polluting this one)

**Comment by nmn** [comment]
For the first problem, I'm asking specifically on how to do Query and Mutation types with annotations. I'll write more in a new issue.

**Comment by hyeluri** [comment]
hi there, any update on this?

**Comment by yrashk** [comment]
Sorry for the delays, it's on Maven Central, finally!
