### ISSUE TITLE
Graphql InterfaceType

### ISSUE THREAD

**Issue by micheal-swiggs** [Enigmatis/graphql-java-annotations#100]
Is it possible to create a Graphql Interface type? At the moment I have a super class with 3 sub classes. Currently I can use the `@GraphQLUnion(possibleTypes={SubClass1.class, SubClass2.class, SubClass2.class})` annotation. However when writing a query I need to state common properties for each class. Instead I would like to state common properties once, and then specify which fields should be returned for each individual class, e.g 

```
  getSubclasses() {
    superclass {
      common_field1
      common_field2
      ... on SubClass1{
          subclass1_field
      }
      ... on SubClass2{
          subclass2_field
      }
  }
```

Is this something that is possible? Is there something like `@GraphQLInterface(possibleTypes={SubClass1.class, SubClass2.class})`?

**Comment by guy120494** [comment]
Hope we get on it this week

**Comment by comtihon** [comment]
Don't know if it helps you,  but to create the interface type, I had to do several steps:

* create interface:
```
public interface Node {
    @GraphQLField
    @GraphQLNonNull
    String id();
}
```
* implement it 
```
public class A implements Node {
    private String id;
    @GraphQLField
    private String fieldA;
    @Override
    @GraphQLField
    public @GraphQLNonNull String id() {
        return id;
    }
}
and 

public class B implements Node {
    private String id;
    @GraphQLField
    private String fieldB;
    @Override
    @GraphQLField
    public @GraphQLNonNull String id() {
        return id;
    }
}
```
* implement type resolver
```
public class NodeTypeResolver implements TypeResolver{
    @Override
    public GraphQLObjectType getType(TypeResolutionEnvironment env) {
        return GraphQLAnnotations.object(env.getObject().getClass());
    }
}
```
* set @GraphQLTypeResolver(NodeTypeResolver.class) to Node:
```
@GraphQLTypeResolver(NodeTypeResolver.class)
public interface Node {
```

After this I am able to do queries with fragments:
```
{node(id: "node_id")
    { 
       id 
       ... on A {fieldA}
       ... on B {fieldB}
     }
}
```

**Comment by guy120494** [comment]
It is nice to have this annotation, but right now I can't add it because grpahql-java doesn't have the right API for that. I opened an [issue ](https://github.com/graphql-java/graphql-java/issues/950)there

**Comment by guy120494** [comment]
please look at #166

**Comment by yarinvak** [comment]
You can create a typeResolver for determining the return type as written above.
