### ISSUE TITLE
Missing dependency in POM to OSGi

### ISSUE THREAD

**Issue by jerrolatqbuzz** [Enigmatis/graphql-java-annotations#102]
The published Maven package is missing a dependency to the OSGi core or annotations package.
This will cause a compile error when extending classes in this project (like GraphQLAnnotations), since the Component annotation cannot be resolved.
It may be related to the OSGi dependencies marked as compileOnly in the build.gradle file.

**Comment by davidstelter** [comment]
Yep, biting me too.

**Comment by guy120494** [comment]
I don't have much time now, as I'm working on another PR. 
You are welcome to make a PR :)
