### ISSUE TITLE
Annotation @GraphQLInvokeDetached Has no effect

### ISSUE THREAD

**Issue by qvistgaard** [Enigmatis/graphql-java-annotations#117]
Using the @GraphQLInvokeDetached annotation has no effect. Adding it to fields does not make i detached / asynchronous

**Comment by guy120494** [comment]
Can you please add the code that makes the problem?

**Comment by tdraier** [comment]
GraphQLInvokeDetached.class has only impacts on method using the MethodDataFetcher, I don't think it does anything on class fields. It just creates a new instance of the class instead of using the source object. No impact on synchronicity of the call.
