### ISSUE TITLE
Update to GraphQL 5.0.0

### ISSUE THREAD

**Issue by nwillc** [Enigmatis/graphql-java-annotations#124]
Any work being done on updating 3.0.3 to 5.0.0?  I did a quick look into it doing it, there were some changes I could not understand how to incorporate.

**Comment by yarinvak** [comment]
We released a new version that supports gql java 5, but havent published it to maven yet.

**Comment by sarathpetec** [comment]
when we can expect 5.0

**Comment by yarinvak** [comment]
updated, you can use the new annotations version 5.0.4

**Comment by nwillc** [comment]
Doh.... so I ditched the annotations over the last week or so and went with IDL to get the GraphQL-java 6.0.  I was a major fan of this annotations kit, but now being familiar with IDL I think I'll stick to that path. This is a good kit, but just in general I'm not an annotations fan as it sprinkles a single concern all over. [My Post About It](https://nwillc.wordpress.com/2017/11/20/graphql-java-6-o/)
