### ISSUE TITLE
Maven repo 

### ISSUE THREAD

**Issue by deventh** [Enigmatis/graphql-java-annotations#136]
How can I use this library in Maven? I found the link in the README.md but is not found:
[![Maven Central](https://img.shields.io/maven-central/v/io.github.graphql-java/graphql-java-annotations.svg?maxAge=2592000)]()

I also found this artifact (I mean looks very similar) in Maven Central: https://mvnrepository.com/artifact/com.graphql-java/graphql-java-annotations. But this one is different! For example in this project `@GraphQLField` annotation located in `graphql.annotations.annotationTypes` package but in this Maven artifact it is here: `graphql.annotations`

**Comment by guy120494** [comment]
https://mvnrepository.com/artifact/io.github.graphql-java/graphql-java-annotations

**Comment by deventh** [comment]
@guy120494 yes, it is working, thank you!
