### ISSUE TITLE
How to use Arrays and other complex data as field arguments

### ISSUE THREAD

**Issue by nmn** [Enigmatis/graphql-java-annotations#14]
If I want to have a field on an object that takes an Array of Strings as an argument, how do I do that with annotations?

The code seems to ignore all parameterized types, so `List<String>` doesn't work.

**Comment by yrashk** [comment]
Actually parametrized lists should work, see tests. Please excuse my
brevity, travelling at the moment

On Wednesday, 1 June 2016, Naman Goel notifications@github.com wrote:

> If I want to have a field on an object that takes an Array of Strings as
> an argument, how do I do that with annotations?
> 
> The code seems to ignore all parameterized types, so List<String> doesn't
> work.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/graphql-java/graphql-java-annotations/issues/14, or mute
> the thread
> https://github.com/notifications/unsubscribe/AAABxGKqURI9hrxmqbpViBGjEQbdBPm0ks5qHbS2gaJpZM4IrvbW
> .

## 

Y.

**Comment by nmn** [comment]
I looked at the tests. It tests return types of methods but not parameterized lists as arguments to methods.

I've got a hack in place for now, but would love to know the correct way to do this when you've got a minute.

**Comment by yrashk** [comment]
Roger that. I think I can see the bug.

**Comment by yrashk** [comment]
Let me know if 3fef70f helps!

**Comment by nmn** [comment]
The tests sure seem to suggest so. Will check with my codebase tomorrow and let you know.
Thanks!

**Comment by yrashk** [comment]
Any updates on this?

**Comment by yrashk** [comment]
@nmn Hi Naman, did you have a chance to check if the proposed solution worked?

**Comment by bbakerman** [comment]
Since no comment was made since Aug 2016 I think this can be closed
