### ISSUE TITLE
Duplicate ConnectionDataFetcher classes

### ISSUE THREAD

**Issue by vinayknl** [Enigmatis/graphql-java-annotations#142]
When using Connections, I could see there are two ConnectionDataFetcher classes (both looks same)
https://github.com/graphql-java/graphql-java-annotations/blob/master/src/main/java/graphql/annotations/connection/ConnectionDataFetcher.java
https://github.com/graphql-java/graphql-java-annotations/blob/master/src/main/java/graphql/annotations/dataFetchers/connection/ConnectionDataFetcher.java

I would assume these are duplicates and only one of them (the second one) is required. Can you please confirm if this is a correct assumption? Thanks

**Comment by guy120494** [comment]
You are right. 
We would be happy if you could PR

**Comment by vinayknl** [comment]
Created https://github.com/graphql-java/graphql-java-annotations/pull/145
