### ISSUE TITLE
ConnectionDataFetcher support for Async executions

### ISSUE THREAD

**Issue by vinayknl** [Enigmatis/graphql-java-annotations#143]
Current ConnectionDataFetcher does not support Async execution and it will be useful to change this to Async.

Something like 
```
public class ConnectionDataFetcher<T> implements DataFetcher<CompletableFuture<graphql.relay.Connection<T>>> {
    @Override
    public CompletableFuture<graphql.relay.Connection<T>> get(DataFetchingEnvironment environment) {
        ConnectionFetcher<T> conn = constructNewInstance(constructor, actualDataFetcher);
        return supplyAsync(() -> conn.get(environment));
    }
}
```
I have tried this locally, please let me know where to find contributing guidelines (or how to contribute) so that i can create a PR for a review.
Thanks,
Vinay

**Comment by guy120494** [comment]
There are no contributing guidelines, just make a PR and we will look at it

**Comment by vinayknl** [comment]
Changed to use Async. PR https://github.com/graphql-java/graphql-java-annotations/pull/144

**Comment by vinayknl** [comment]
Can someone please review the PR ? Would like to get some feedback as we are planning to use this in our project.

**Comment by guy120494** [comment]
@yarinvak and I will look at it tomorrow

**Comment by vinayknl** [comment]
Thanks for quick response.

**Comment by vinayknl** [comment]
PR https://github.com/graphql-java/graphql-java-annotations/pull/144 is updated to make async optional. Can someone please check.
Thanks,
vinay

**Comment by guy120494** [comment]
PR #144 merged

**Comment by vinayknl** [comment]
Thanks for merging and closing this PR. Is there any plans to release a new version with the latest fixes ? We would like to use them in our project. Regards, Vinay

**Comment by guy120494** [comment]
We just released the new version (5.2)

**Comment by vinayknl** [comment]
@guy120494 Thanks for responding, but 5.2 does not seem to contain the fix for this issue. Is it possible to check on this ? Ta

**Comment by guy120494** [comment]
Well, 5.2 contains your PR. Do you have any idea why doesn't it work?

**Comment by vinayknl** [comment]
Manifest looks latest, but the code for ex: GraphQLConnection annotation class does not contain new Param (async). So not sure if the souce used for build is from after merge of this PR

**Comment by vinayknl** [comment]
![87c72e4a-858b-4325-98cb-b6691e6b80ce](https://user-images.githubusercontent.com/3449829/37360283-108c03be-26f0-11e8-8e7e-597f6abaf6a2.png)

**Comment by guy120494** [comment]
@yarinvak can you upload a new version to maven?
