### ISSUE TITLE
Release new fixes.

### ISSUE THREAD

**Issue by comtihon** [Enigmatis/graphql-java-annotations#146]
Hi,
Please release new fixes, introduced in https://github.com/graphql-java/graphql-java-annotations/commit/1086e38b079de4804e39ebf1d1946cb43a2b5875
I have problems with imput enums without them.

**Comment by guy120494** [comment]
We will release the new version (along with the PR that wait) probably next week

**Comment by yarinvak** [comment]
Version 5.1 released https://mvnrepository.com/artifact/io.github.graphql-java/graphql-java-annotations/5.1
