### ISSUE TITLE
Java Map as argument.

### ISSUE THREAD

**Issue by rsmkrishna** [Enigmatis/graphql-java-annotations#147]
Hi,

Team, Thanks for a wonderful framework. 

In plain graphql-java, we can create own scalartype. In graphql-java-annotation, how to define new scalar type and register. Say I am trying to pass a Java Map object as argument in query. Kindly guide me.

**Comment by vinayknl** [comment]
https://github.com/graphql-java/graphql-java-annotations/blob/master/src/test/java/graphql/annotations/GraphQLInputTest.java#L74

This test has some examples (not direct ones), but using Map's should work in a similar way.
