### ISSUE TITLE
Float imput type is not working.

### ISSUE THREAD

**Issue by comtihon** [Enigmatis/graphql-java-annotations#148]
Hi,
This test can't pass:
```
    public static class FloatQuery {
        @GraphQLField
        public Integer floatToInt(@GraphQLNonNull @GraphQLName("data") Float data) {
            return data.intValue();
        }
    }

    @Test
    public void floatIntQuery() {
        GraphQLSchema schema = newSchema().query(GraphQLAnnotations.object(FloatQuery.class)).build();
        GraphQL graphQL = GraphQL.newGraphQL(schema).build();
        ExecutionResult result = graphQL.execute("{ floatToInt ( data:15.0 ) }", new FloatQuery());
        assertTrue(result.getErrors().isEmpty());
        assertEquals(((Map<String, Integer>) result.getData()).get("floatToInt"), Integer.valueOf(15));
    }
```
Instead of data it returns error:
`ExceptionWhileDataFetching{path=[floatToInt]exception=java.lang.IllegalArgumentException: argument type mismatchlocations=[SourceLocation{line=1, column=3}]}`

**Comment by yarinvak** [comment]
Please try the new version 5.1 and let us know if it still breaks

**Comment by comtihon** [comment]
ok

**Comment by yarinvak** [comment]
Hey, I checked it, the ``GraphQLFloat`` sclara is equivalent to Double in java.
So you should use Double and not Float in your types.

**Comment by yarinvak** [comment]
confusion solved here: https://github.com/graphql-java/graphql-java-annotations/issues/148
