### ISSUE TITLE
Jdk version

### ISSUE THREAD

**Issue by xumingming** [Enigmatis/graphql-java-annotations#15]
This lib is awesome, make GraphQL less verbose to use in Java, thanks!

But it looks like that this lib depends on jdk 1.8, is there any particular reason for this? our production code is still using jdk1.6, but want to use this lib.

**Comment by yrashk** [comment]
Hi, thank you for your kind words.

There was no particular reason besides the fact that I use 1.8 in my work. I'd gladly accept a PR that enables usage of 1.6 for this library! Let me know if you have any questions.

**Comment by He-Pin** [comment]
@xumingming If you want to user lower version,you must figure out how to get the method parameter name.

**Comment by He-Pin** [comment]
@xumingming I see you are work at Alibaba,please contact me with 虎鸣 as the internal nick name.

**Comment by yrashk** [comment]
there's a workaround for that — using `@GraphQLName` with parameters. Not beautiful, but should work.

**Comment by He-Pin** [comment]
@yrashk Yes,another way is using the Spring or Reflections,both will introduce third part dependency,I don't know will Java Annotation Processor helps here,like a macro,but that will complicate things too.

**Comment by xumingming** [comment]
@yrashk Thanks for the quick response, I will try to adapt this lib to jdk1.6 and submit a pull request.

**Comment by xumingming** [comment]
there are indeed quite a bit java8 specific java class used:

``` java
import java.lang.reflect.AnnotatedType;
import java.util.function.BiFunction;
import java.lang.reflect.AnnotatedParameterizedType;
import java.lang.reflect.AnnotatedType;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ConcurrentHashMap;
import java.util.function.BiFunction;
import java.util.stream.Stream;
```

**Comment by yrashk** [comment]
Not sure if this will help, but just in case:
https://github.com/orfjackal/retrolambda

**Comment by apottere** [comment]
According to [this](http://graphql-java.readthedocs.io/en/latest/getting_started.html), graphql-java now requires java 1.8.
