### ISSUE TITLE
Where is @GraphQLQuery

### ISSUE THREAD

**Issue by yangxy81118** [Enigmatis/graphql-java-annotations#150]
In many articles, I found they used @GraphQLQuery , but where is it ?

**Comment by guy120494** [comment]
There is no need for `@GraphQLQuery`, as the `Qeruy` object is registered to the schema via `GraphQLObjectType queryRoot= GraphQLAnnotations.object(QueryRoot.class);`, and then set the `queryRoot` as the query object in the schema via `GraphQLSchema schema = newSchema().query(object).build();`
The rest is already defined in the annotations, so the library knows how to build the schema
