### ISSUE TITLE
Release v5.0 on maven central repo

### ISSUE THREAD

**Issue by mertergun** [Enigmatis/graphql-java-annotations#152]
Hello guys,
A newbie here. I am super dumb not to see it or the new release v5.0 is not on [the maven central repository](https://mvnrepository.com/artifact/com.graphql-java/graphql-java-annotations). Can you help me find it ? Or if it isn't there yet, what is the planned date to update maven central repo?

**Comment by guy120494** [comment]
https://mvnrepository.com/artifact/io.github.graphql-java/graphql-java-annotations
