### ISSUE TITLE
Need for an example

### ISSUE THREAD

**Issue by anediaz** [Enigmatis/graphql-java-annotations#16]
Hi,
This is not really an issue but a request.
Could be possible to have an example of a complete schema using graphql-java-annotations?
I have tried to look for examples but I haven't found anything I could be based on.

Thanks in advance.

Ane

**Comment by liaofangcai** [comment]
Same feeling

**Comment by orefalo** [comment]
How you looked at the tests?

**Comment by laurentpellegrino** [comment]
The project looks really good but some more examples and especially documentation would help people like me who are beginners with GraphQL. Some tests are not obvious to understand. Also, a guide to develop some common use cases would be interesting.

**Comment by orefalo** [comment]
I can't disagree as I am myself trying to figure how Union types work.. ;-)

**Comment by jleufven** [comment]
Same here, trying to figure out how you're supposed to use `@GraphQLMutation`.

My problem: You can annotate a class with `@GraphQLMutation` and then add it to your schema mutations  using `GraphQLAnnotations.object`, great! But when executing a query it returns `null`. Looks like `MethodDataFetcher.get` expects you to execute the query with an instance of the annotated class as `context` (otherwise `MethodDataFetcher.get...environment.getSource()` returns null). This works, if you only have one class with mutations, but I'd like to spread them over several classes, and I can't know which `context` to pass to execute.

**Comment by jleskovar** [comment]
I'm also a little bit confused about how you're meant to implement a stateful data fetcher. For example, suppose I declare a data fetcher method that requires interrogating a Spring JPA repository as part of its implementation. How would I go about fetching the repository, apart from exposing it in a public global accessor? Is it possible to "wire in" non GraphQL parameters on the data fetcher method that I can specify at schema creation time?

For example:
```
...
  @GraphQLField
  public String field(DataFetchingEnvironment env, MyJpaRepository repo, String value) {
    return repo.getByField(value);
  }
...
```

**Comment by titusgahissy** [comment]
To "wire in" spring components, I use the context argument when calling `execute`:

```kotlin
// appContext is an @Autowired ApplicationContext
// Repositories is a Spring Class that helps you 
// retrieve your JpaRepository with `getRepositoryFor(EntityClass)`

graphQL.execute(requestString, operationName, Repositories(appContext), arguments)
```
Hope that helps.

**Comment by jleskovar** [comment]
Thank you!

**Comment by shishuwu** [comment]
Cannot agree more.

If more samples and documentation work is done, i suppose it will attract more developers and get more stars...

**Comment by ollifer** [comment]
Guys, do you have any proper example how can we inject or just pass dao or repository, or smth else into particular DataFetcher class. Is there only way to fetch such objects via context like this?

```
@Override
    public List<Entity> get(DataFetchingEnvironment environment) {
       Dao dao= ((Map<String, Object> )environment.getContext()).get(DAO_BEAN_KEY);
        return dao.findAll();
    }
```

**Comment by kliakos** [comment]
Very nice tutorial here http://www.baeldung.com/graphql
