### ISSUE TITLE
Type resolver for union types

### ISSUE THREAD

**Issue by alonkashtan** [Enigmatis/graphql-java-annotations#162]
The ability of type resolver should be added to union type annotation, similar to the way it is in interfaces.

The problem that accrues without a type resolver is that in case that the fetcher returns a type that is different then what is declared by the field, an exception is thrown.

For example:
```java
@GraphQLUnion(possibleTypes = { Computer.class, Screen.class })
interface Hardware {}

class Computer implements Hardware {
    String name();
}

// Hibernate class with same structure of API class
class ComputerDB {
    String name;
}

class Query{
    @GraphQLField
    @GraphQLDataFetcher(HardwareFetcher.class)
    public Hardware getHardware() { return null; }    
}

class HardwareFetcher implements DataFetcher<ComputerDB> {
    public ComputerDB get() {
        // returns a computer from DB
    }
}
```
This scenario can be implemented without using Union (and often is) but when using union type I get an exception that states that the type ComputerDB is not in the possible types.
A type resolver would allow me to implement this scenario, similar to how it would work in an interface.

**Comment by guy120494** [comment]
Did you try annotate the class with `@GraphQLTypeResolver`?

**Comment by guy120494** [comment]
#165 fixes it
