### ISSUE TITLE
NullPointerException in MethodDataFetcher when using methods

### ISSUE THREAD

**Issue by alonkashtan** [Enigmatis/graphql-java-annotations#168]
I often use DataFetchers that return an object of a different type then the one defining the GraphQL type, but with the same structure. I found a problem with using this technique when the GraphQL type includes a method.

For example:
```Java
@GraphQLType
class ApiType {
    @GraphQLField
    public int a() {return 0;}
}

class InternalType{
    public int a;
}

@GraphQLType
class Query{
    @GraphQLField
    @GraphQLDataFetcher(MyFetcher.class)
    public ApiType field;
}

class MyFetcher implements DataFetcher<InternalType>{
    public InternalType get(DataFetchingEnvironment environment){
        return new InternalType();
    }
}
```
Querying `query{ field }` will cause a `NullPointerException`.

This is caused because in [MethodDataFetcher](https://github.com/graphql-java/graphql-java-annotations/blob/e12018808e6c95319a97f15c09b5450306a77cce/src/main/java/graphql/annotations/dataFetchers/MethodDataFetcher.java#L55) there is a search for a constructor that receives the actual type, and if none is found returns null that is not handled [later](https://github.com/graphql-java/graphql-java-annotations/blob/e12018808e6c95319a97f15c09b5450306a77cce/src/main/java/graphql/annotations/dataFetchers/MethodDataFetcher.java#L62).

Please note that I am sometimes required to use methods instead of fields because we want to use GraphQL interfaces or union types, which require implementing Java interfaces and thous using methods.

The behavior I would expect in this case is that the field value will be copied from the returned objects, as with fields (handled by graphql-java's `PropertyDataFetcher`).

**Comment by osher-sade** [comment]
Fixed in #172
