### ISSUE TITLE
No field prettify by dfault

### ISSUE THREAD

**Issue by tdraier** [Enigmatis/graphql-java-annotations#181]
All fields are now by default generating a name from the method without removing the get/is - we need to add @GraphQLPrettify . That could make sense, but completely breaks the compatibility since the schema is now generating field names with get/is. On my side it requires updating about 300+ fields in different repositories. Would it be possible to set prettify as a default somehow ? The FieldNameBuilder does not seem configurable at all, so I cannot change its behaviour. 

Also, maybe a side effect of this, I now need to add a @GraphqlField @GraphQLPrettify on subclasses that implement interfaces, where it was only needed on the interface before.

**Comment by yarinvak** [comment]
https://github.com/graphql-java/graphql-java-annotations/issues/177 is addressing the same thing.
I see your point, it will be wise to add a default strategy that prettifies the fields for compatibility.

**Comment by yarinvak** [comment]
I have merged your PR.
Thanks :)
