### ISSUE TITLE
Next release ?

### ISSUE THREAD

**Issue by sergehuber** [Enigmatis/graphql-java-annotations#188]
Hi sorry for using a ticket for this but I couldn't find any other way to get in touch with the project now that it is no longer at graphql-java.com

I would really like to help getting a release out. I need a release that includes the pull request that was merged. How can I help make this happen ?

Regards,
  Serge...

**Comment by yarinvak** [comment]
Hey!
We will try to release a new version next week

**Comment by sergehuber** [comment]
Thanks a lot, let me know if I can help, looking forward to the release !

**Comment by yarinvak** [comment]
We would like to upgrade to the new graphql-Java version before we release, so it can be helpful if you PR this :)

**Comment by sergehuber** [comment]
Ok I did a PR to support graphql-java 11 but there seems to be an issue with the build platform as it builds fine locally.
Here's the PR : https://github.com/Enigmatis/graphql-java-annotations/pull/189

**Comment by sergehuber** [comment]
I'm not sure what's going on but I tried to do the PR once again and still got the same error from Google Cloud. Maybe there is some remaining configuration somewhere ?

**Comment by sergehuber** [comment]
I'm sorry to insist but I need a release to be able to commit in a project that is using graphql-java-annotations. I think I'm going to have to fork it and upload the forked versions to Maven Central as this process is quite long. I was hoping to avoid this.

**Comment by yarinvak** [comment]
Hey if you wish you can fork it in the meantime, we are having troubles with fixing the build issues.
We are trying to do our best, I hope it will be fixed in the next days.
Anyway I can release a new version earlier if we wont be able to merge your PR soon

**Comment by sergehuber** [comment]
Ok I realize now my message might have been a bit harsh. I really want to help as much as possible but I feel like I can't do much more with my current access on the project. I'm more than willing and available to do some more build tests if you need them.
I do think it would make sense to do the release with the PR though.
I'll see on my side if I fork but I think in this project we should do things the proper way. Thank you very much for your time and your commitment to this project !

**Comment by yarinvak** [comment]
Thanks a lot for your contribution. It is something in our configurations and I will look into it soon, I had some busy days lately. 

Let you know if there are some news

**Comment by yarinvak** [comment]
Thanks a lot for your contribution. It is something in our configurations and I will look into it soon, I had some busy days lately. 

Let you know if there are some news

**Comment by yarinvak** [comment]
v6.1 was released :)

**Comment by sergehuber** [comment]
This is GREAT news thank you so much !
