### ISSUE TITLE
ClassCastException With 6.2

### ISSUE THREAD

**Issue by richharms** [Enigmatis/graphql-java-annotations#197]
Noticed that 6.2 had been released today, and am running into an issue after upgrading to it and graphql-java 11.0 when attempting to retrieve the introspection query:

```
Caused by: java.lang.ClassCastException: graphql.schema.GraphQLNonNull cannot be cast to graphql.schema.GraphQLObjectType
	at graphql.annotations.strategies.EnhancedExecutionStrategy.resolveField(EnhancedExecutionStrategy.java:34)
	at graphql.execution.AsyncSerialExecutionStrategy.lambda$execute$1(AsyncSerialExecutionStrategy.java:43)
	at graphql.execution.Async.eachSequentiallyImpl(Async.java:75)
	... 93 more
```

Haven't totally pinned down what's changed, but I wanted to report this since it looked like 6.2 is on its way to being released and the line causing the exception was modified as part of the upgrade to graphql-java 11.0.

**Comment by chenshoo** [comment]
hey, can you elaborate on the query you tried? i'm trying to raise this exception, but I need more details.

**Comment by richharms** [comment]
I was using Insomnia as the client to do a quick test to try out the new library versions (upgraded graphql-java-annotations and graphql-java), and the exception occurred when it tried to execute the introspection query. For the application I had deployed, it was just IntrospectionQuery.INTROSPECTION_QUERY (IntrospectionQuery = graphql.introspection.IntrospectionQuery).

I don't have an small example to share (yet), but the two classes in the application that define the queries and mutations are here:

- [GraphQlMutations.java](https://github.com/echothreellc/echothree/blob/master/src/java/com/echothree/model/control/graphql/server/util/GraphQlMutations.java)
- [GraphQlQueries.java](https://github.com/echothreellc/echothree/blob/master/src/java/com/echothree/model/control/graphql/server/util/GraphQlQueries.java)

**Comment by richharms** [comment]
Finally was able to return to looking at this today, and was able to come up with a fix for it. I've created a PR for it.
