### ISSUE TITLE
What's the status of development on this project?

### ISSUE THREAD

**Issue by sanderkoenders** [Enigmatis/graphql-java-annotations#205]
I am using graphql annotations for my project but I am in the process of upgrading graphql to one of the later versions (9.5 or 12). I am looking at the options I have and it seems like this library is no longer maintained because the activity in terms of commits is relatively low. The latest release  (v6.0) released in october 2018 says:

`IT WASNT RELEASED CORRECTLY AND WILL BE FIXED SOON`

Since then there has been no sign of a newer version. This version should support version 9.2 of Graphql. What would be the advice going forward from this? Should I remove the annotation library entirely and do it the official graphql way? Or can I still use this library? What's the status on development on this library?

**Comment by yarinvak** [comment]
The latest release is 6.2 which supports graphql-java 11.0.
We are still maintaining this project but there are no major issues to address right now. 
In terms of upgrading the graphql-java dependencies we call the community to open PRs / issues if we do not do it in time and we will address it

**Comment by sanderkoenders** [comment]
I am just getting started on a project that uses both graphql and this annotation library which was maintained by another developer before. I am not to familiar with Graphql, the annotations and their workings so I am afraid a pull-request to support the newer versions of Graphql would not be easy to make for me personally. I do see that graphql version 12 was released back in March this year, is there any ETA on when this version will be officially supported by this annotations library?

**Comment by yarinvak** [comment]
Most of the features that graphql-java releases in their newer versions are features for the schema-first method of creating a graphql server.
The annotations library do not use these features at most cases, so upgrading is not always necessary. 
I guess soon we will be available to work on upgrading to graphql-java 12. Of course you do not have to create PRs yourself but it will be great if you create issues for changes/upgrades/features you would like us to address in our development (like upgrading to gql java 12).

Thanks :)

**Comment by sanderkoenders** [comment]
https://github.com/Enigmatis/graphql-java-annotations/issues/206
