### ISSUE TITLE
Upgrade to Grapqhql 12

### ISSUE THREAD

**Issue by sanderkoenders** [Enigmatis/graphql-java-annotations#206]
As the title says, it would be nice to have an official release for Graphql 12.

**Comment by yarinvak** [comment]
I looked into graphql-java 12. Their API breakers are significant, it will take us a while to handle their new CodeRegistry and maybe we will have to break our API as well.
I've added it to a v7 milestone, but we are on a holiday so it will take us a while to begin working on it.

**Comment by yarinvak** [comment]
merged into development and will be released soon

**Comment by sanderkoenders** [comment]
Thank you for implementing support for Graphql 12.
