### ISSUE TITLE
GraphQLAnnotations causes ClassCastException

### ISSUE THREAD

**Issue by shevek** [Enigmatis/graphql-java-annotations#235]
GraphQLAnnotations.java:
```
    public GraphQLObjectType object(Class<?> object) throws GraphQLAnnotationsException {
```

It's legitimate for this to be a GraphQLUnionType, which does not extend GraphQLObjectType. The sub-method being called has type `<T [extends ...]> T`

**Comment by yarinvak** [comment]
but the method object generates only `GraphQLObjectType`s, so creating a `GraphQLUnion` using this method is incorrect

**Comment by shevek** [comment]
Yes, but an unadorned CCE isn't the most helpful way to tell the user that.
