### ISSUE TITLE
Interfaces not detected when referenced by supertype

### ISSUE THREAD

**Issue by shevek** [Enigmatis/graphql-java-annotations#236]
```
@GraphQLTypeResolver(...) public interface MyInterface {}
public abstract class Base implements MyInterface {}
@GraphQLName("value") public  class Value extends Base{}
```

In the generated schema, Value does *not* implement MyInterface, and it should.

**Comment by shevek** [comment]
If I do `Value extends Base implements MyInterface` then it does work, but this is (in Java terms) redundant

**Comment by yarinvak** [comment]
GraphQL Schema does not support multiple levels of inheritance for now, so it will not work

**Comment by shevek** [comment]
See #238 for a note on why I think the real value is in compiling Java semantics into GraphQL semantics. I'm thinking like a product designer here, not just a programmer.
