### ISSUE TITLE
Autodetect GraphQL interfaces

### ISSUE THREAD

**Issue by shevek** [Enigmatis/graphql-java-annotations#237]
If an object implements an interface with GraphQL annotations on it, that interface should be autodetected and added to the schema.

```
@GraphQLTypeResolver(...)
public interface MyIF{}
public class Foo implements MyIF {}

annotations.additionalType(Foo.class);
```

Should detect MyIF, and does not.

**Comment by Fgerthoffert** [comment]
Hi @shevek,

We don't believe this is relevant (and this would introduce breaking changes), this annotation can be added directly added to your class explicitly (instead of auto-detecting).

Thanks
