### ISSUE TITLE
Add support for batched data fetchers

### ISSUE THREAD

**Issue by ceronman** [Enigmatis/graphql-java-annotations#24]
When using a `BatchedExecutionStrategy`, `graphql-java` requires the `get` method of the data fetcher to be decorated with the `@Batched` annotation. 

Currently the only way of using batched fetchers with `graphql-java-annotations` is to use a custom `@GraphQLDataFetcher`. I think this can be solved by adding a new annotation called `GraphQLBatched` that can be added to methods and then a special subclass of `MethodDataFetcher` should internally use the `@Batched` annotation.

If you agree with this approach I can provide a PR.

**Comment by yrashk** [comment]
Please do!
