### ISSUE TITLE
GraphQL Java 15 Support

### ISSUE THREAD

**Issue by setchy** [Enigmatis/graphql-java-annotations#259]
Keen to start a discussion around updating to support GraphQL Java 15.

I have these two related PRs and having io.github.graphql-java:graphql-java-annotations support graphql-java:15 is a dependency
- https://github.com/graphql-java-kickstart/graphql-java-servlet/pull/270
- https://github.com/graphql-java-kickstart/graphql-spring-boot/pull/461

**Comment by setchy** [comment]
Pull Request #260

**Comment by setchy** [comment]
Merged and released - v8.2 - https://github.com/Enigmatis/graphql-java-annotations/releases/tag/v8.2

**Comment by yarinvak** [comment]
Thanks for the contribution
