### ISSUE TITLE
Update to use graphql-java:16.1

### ISSUE THREAD

**Issue by setchy** [Enigmatis/graphql-java-annotations#269]
graphql-java:16.1 was released late last year.  Would be good to update and release a version of graphql-java-annotations that uses this

**Comment by yarinvak** [comment]
would appreciate a PR for that matter
otherwise will address it when available later on

**Comment by anttip** [comment]
Added a PR suggestion for this: https://github.com/Enigmatis/graphql-java-annotations/pull/270
