### ISSUE TITLE
Updating to v17.0

### ISSUE THREAD

**Issue by softshape** [Enigmatis/graphql-java-annotations#273]
Any plans to release with Java GraphQL 17.0 ?

**Comment by yarinvak** [comment]
There's a pending PR https://github.com/Enigmatis/graphql-java-annotations/pull/272 for this, we will consider merging it in the following days

**Comment by setchy** [comment]
#277 PR had been merged awaiting a release

**Comment by yarinvak** [comment]
Released, will take a couple of hours before synced with maven-central.
Thanks for your contribution @setchy
