### ISSUE TITLE
OSGi Metadata not properly generated

### ISSUE THREAD

**Issue by sergehuber** [Enigmatis/graphql-java-annotations#283]
Following the upgrade of Gradle and the BND plugin, the OSGi metadata is not properly generated anymore, it puts all the packages in the JAR as Private instead of being exported (basically rendering the JAR useless in an OSGi environment). 

It seems the fix is relatively easy, simply rename the bundle.bnd file to bnd.bnd. I will submit a PR for this.

**Comment by geichelberger** [comment]
Hi, is there a plan for when the next release will come? Especially with the corrected OSGi metadata and graphl-java update.
