### ISSUE TITLE
Any way to handle map object when generating schema

### ISSUE THREAD

**Issue by PeterFan89** [Enigmatis/graphql-java-annotations#285]
I'm using annotation to generate graphql schema. However, it didn't work when the annotation handle map object. For example, I put the @GraphQLField on the field which type is like Map<Integer, ObjectA> and also have @GraphQLField on the field inside the object. Then I print the schema but cannot find the ObjectA type in my schema. Is there any way I can handle map object?

**Comment by sergehuber** [comment]
Is this still relevant or can we close this issue ?

**Comment by Fgerthoffert** [comment]
Hi @PeterFan89,

Are you still interested in this? 

If not, or without a response from you we will close this ticket during our next backlog review in a month.

Thanks

**Comment by PeterFan89** [comment]
Hi there,
It is OK to close the ticket.

Thanks

Francois G. ***@***.***> 于2024年1月10日周三 18:06写道：
