### ISSUE TITLE
Couldn't get private field in object

### ISSUE THREAD

**Issue by mwkang** [Enigmatis/graphql-java-annotations#29]
Hello, I try to use graphql-java-annotations in my project.
But `@GraphQLField` does not work in private field.
Do you have a plan support this feature?
My graphql-java-annotations's version is 0.11.0

**Comment by yrashk** [comment]
I just published 0.12.0 with support for private fields (kudos to @TKffTK), will be available on Maven Central within a couple of hours. Please let me know if this solves your problem.

**Comment by mwkang** [comment]
Oh, Thanks for your comment.
I will leave comment if it is solves.
And Could I ask for this project roadmap?
Or What dose project focused on now?

**Comment by mwkang** [comment]
@yrashk 0.12.0 can read private fields. thanks! :)
