### ISSUE TITLE
Method data fetcher on root query

### ISSUE THREAD

**Issue by alexkrebiehl** [Enigmatis/graphql-java-annotations#3]
I am trying to leverage your package to make a schema builder.  To do this, I scan my package for a certain class annotation, and construct a `GraphQLObjectType` from any of those classes found.

I'm having a problem with the MethodDataFetcher on methods using this approach (the `GraphQLDataFetcher` annotation with a separate data fetching class works).  When the MethodDataFetcher tries to resolve the field, `environment.getSource()` is `null` and the fetcher returns `null`.  This only appears to be a problem for fields defined on the QueryRoot.

A root fields node may be defined like this:

``` java
class ModelRootQueries {
  public Model modelById(@GraphQLName("id") String id) {
    // never invoked
    return ModelService.get(id);
  }
}
```

I am constructing my QueryRoot like so:

``` java
GraphQLObjectType node = GraphQLAnnotations.newObject(ModelRootQueries.class);
root.fields(node.getFieldDefinitions();
...
GraphQLSchema schema = newSchema.query(root).build();
```

In this case, the body of the method is never called, and `data` ends up being `null`.

I'd appreciate some insight into whether I'm wiring it incorrectly, or if there's a problem with the MethodDataFetcher's implementation.

Thanks, 
Alex

**Comment by yrashk** [comment]
Hi Alex,

Thanks for submitting this issue. I am going to look at it shortly. Meanwhile, is there any chance you can produce the smallest possible finite example I can run as a test to reproduce the exact problem? That will help me figuring out what's wrong.

**Comment by yrashk** [comment]
First thing I noticed is that you don't have `@GraphQLField` applied to `modelById` — is that the case in the actual code you are working with?

**Comment by yrashk** [comment]
Second thing is that you are borrowing fields from one object to another, yet the data fetcher can't possible know you are doing this. Therefore (as you mentioned) only a custom data fetcher specified through an annotation would be able to fetch information from these "sister" objects.

As a matter of fact, I am using a very similar scanning scheme in my projects. However, I don't borrow the fields over but rather expose every class through an individual field in the root object. You can find my implementation here: https://github.com/eventsourcing/es4j-graphql/blob/master/src/main/java/com/eventsourcing/graphql/GraphQLServlet.java#L65-L72

Is this helpful at all?

**Comment by alexkrebiehl** [comment]
Thanks for the quick reply.  I actually did have `@GraphQLField` on my method, and it it does get parsed by GraphQLAnnotations.

Here is an example of what I'm currently doing (I tried to add it to my GitHub, but can't where I am at now).

``` java
public class Builder {

    public static void main(String... args) throws IllegalAccessException, NoSuchMethodException, InstantiationException {
        GraphQLSchema schema = generateSchema();

        GraphQL graphQl = new GraphQL(schema);
        Object data = graphQl.execute("query{sampleQuery(id:3)}").getData();
        System.out.println("Result: " + data);
    }

    public static GraphQLSchema generateSchema() throws IllegalAccessException, NoSuchMethodException, InstantiationException {
        GraphQLObjectType.Builder queryRoot = GraphQLObjectType.newObject();
        queryRoot.name("QueryRoot");


        GraphQLObjectType.Builder querySpaceBuilder = GraphQLObjectType.newObject();
        GraphQLObjectType node = GraphQLAnnotations.object(QueryRootExample.class);
        for ( GraphQLFieldDefinition field : node.getFieldDefinitions() ) {
            queryRoot.field(field);
        }

        return newSchema().query(queryRoot.build()).build();
    }
}
```

``` java
@GraphQLName("SampleName")
public class QueryRootExample {
    @GraphQLField
    public int sampleQuery(@GraphQLName("id") @NotNull int id) {
        return id;
    }
}
```

I also tried making fields on the root node similiar to the way you were in the example, but getting stuck on what to use for the static value:

``` java
GraphQLObjectType.Builder querySpaceBuilder = GraphQLObjectType.newObject();
GraphQLObjectType node = GraphQLAnnotations.object(QueryRootExample.class);
for ( GraphQLFieldDefinition field : node.getFieldDefinitions() ) {
    queryRoot.field(GraphQLFieldDefinition.newFieldDefinition()
            .type(node)
            .name(node.getName())
            .staticValue(???)
            .build()
     );
}
```

Thanks again,
Alex

**Comment by yrashk** [comment]
Alex, static value should be an instance of the class you have the object definition for. Like, if you have

``` java
public class SomeClass {
  @GraphQLField
  public String field;
}
```

and it is being picked up by your scanner, then the corresponding static value would be `new SomeClass()` (you can do that with `newInstance()` or follow my example in es4j-graphql and introduce a discovery interface similar to `GraphQLQueryProvider` (https://github.com/eventsourcing/es4j-graphql/blob/master/src/main/java/com/eventsourcing/graphql/GraphQLQueryProvider.java) so that you can have a method that returns an instance)

Does this help?

**Comment by alexkrebiehl** [comment]
Thank you, that was very helpful.  Making a new instance to assign as a static value was the piece I was missing.  Thanks for all of your help!

**Comment by yrashk** [comment]
Alex,

I just extracted https://github.com/yrashk/graphql-java-servlet to provide a common servlet implementation to be used in this scenario. May be you can find it useful for your needs, and if you think it is missing something, I'd be happy to improve it!
