### ISSUE TITLE
Update graphql-java to 21.5 once graphql-java-annotations 21.2 is released.

### ISSUE THREAD

**Issue by Fgerthoffert** [Enigmatis/graphql-java-annotations#300]
We're expecting the release of 21.2.0 to happen within a month.

_Internal ticket: TECH-1768_

**Comment by geichelberger** [comment]
Hi,

Is there a chance this bug fix (https://github.com/Enigmatis/graphql-java-annotations/pull/301) can be part of the 21.2 release?

Thanks

**Comment by sergehuber** [comment]
Hello @geichelberger, 

Unfortunately this bug fix (thanks for the bug fix btw) can't be included in the 21.2 release because we need to review it. We are ready to cut 21.2 which should happen soon so your fix will be included in the release after 21.2, hopefully soon after.
