### ISSUE TITLE
Publish action failing due to invalid token

### ISSUE THREAD

**Issue by jkevan** [Enigmatis/graphql-java-annotations#305]
While working on: https://github.com/Enigmatis/graphql-java-annotations/issues/302
During the release, I started a publish action: https://github.com/Enigmatis/graphql-java-annotations/actions/runs/9745767091/job/26894508281

But it's failing due to:
```
Execution failed for task ':publishMavenPublicationToSonatypeRepository'.
> Failed to publish publication 'maven' to repository 'sonatype'
   > Could not PUT 'https://oss.sonatype.org/service/local/staging/deployByRepositoryId/iogithubgraphql-java-1070/io/github/graphql-java/graphql-java-annotations/21.5/graphql-java-annotations-21.5.jar'. Received status code 401 from server: Content access is protected by token
```

May be token is expired and need to be updated ?

**Comment by geichelberger** [comment]
Do you know if there is any news about the problem yet?

**Comment by Fgerthoffert** [comment]
Yes, we recovered push permissions to maven central, the release should be done soon.

**Comment by jkevan** [comment]
Version 21.5 is now released and available in maven central repository.
