### ISSUE TITLE
Unions?

### ISSUE THREAD

**Issue by orefalo** [Enigmatis/graphql-java-annotations#31]
How would you define a Union type?

**Comment by astarz41** [comment]
There is a small example here https://github.com/graphql-java/graphql-java-annotations/blob/master/src/test/java/graphql/annotations/GraphQLInterfaceTest.java

It's basically an interface with @GraphQLUnion annotation stating the possible types: @GraphQLUnion(possibleTypes = TestObject1.class)

**Comment by xSeagullx** [comment]
Am I right, that it currently works only for interfaces?
I have an abstract class, and I want to query a List of them. 
```
abstract class Abstract {
  String id
}

class Concrete extends Abstract {
  
}

class SomeBean {
  List<Abstract> values;
}
```

Query like `{ values { id, __typename } ) }` yields: `{ values: [ { 1, "Abstract" }, { 2, "Abstract" } ] }`

Any ideas?

**Comment by TuomasKiviaho** [comment]
The spec only forbids using interfaces as possible types, but even there the java interface should not be treated always to yield to a schema interface . 

I commented out the problematic interface testing and it worked like charm. Now I can mimic the `@XmlElementWrapper` behaviour from JAXB without breaking backwards compatibility.

``` java
    public GraphQLUnionType.Builder getUnionBuilder(Class<?> iface, ProcessingElementsContainer container) throws GraphQLAnnotationsException, IllegalArgumentException {
        if (!iface.isInterface()) {
            throw new IllegalArgumentException(iface + " is not an interface");
        }
```

the only odd thing is that I get empty objects `{}` for those instances that I don't even want to receive.
