### ISSUE TITLE
Optional return type on GraphQLField annotation is not working

### ISSUE THREAD

**Issue by tnithinreddy** [Enigmatis/graphql-java-annotations#32]
I used @GraphQLField for the field name and it returned the Optional type too 
{"query":
      {
         "name": "Optional[John Doe]"
      }
}

**Comment by yrashk** [comment]
Thanks for opening the issue! Can you provide a test case against https://github.com/graphql-java/graphql-java-annotations/blob/master/src/test/java/graphql/annotations/GraphQLObjectTest.java#L491-L500 ?

Also, I am wondering, are you using EnhancedExecutionStrategy or not? It's taking care of Optional. If you will look into the test, you will see its using EnhancedExecutionStrategy

**Comment by tnithinreddy** [comment]
thanks @yrashk 
I looked at the source, im actually using "graphql-java-servlet" package, (GraphQLServlet),  which has a method executeQuery(), which actually creates a new GraphQl object,

```
ExecutionResult result = new GraphQL(schema).execute(query, createContext(Optional.empty(), Optional.empty()), new HashMap<>());
```

but it does not use any execution strategy.

It should also take in the execution strategy, it should be like this

```
ExecutionResult result = new GraphQL(schema, executionStrategyProvider).execute(query, createContext(Optional.empty(), Optional.empty()), new HashMap<>());
```
