### ISSUE TITLE
Arguments for a field annotated with @GraphQLConnection

### ISSUE THREAD

**Issue by laurentpellegrino** [Enigmatis/graphql-java-annotations#33]
I have a query type with a field named _jobs_:

```
@GraphQLField
@GraphQLConnection
public List<Job> jobs(JobInput jobInput) {
    ....
}
```

This last field defines an InputType in order to pass some arguments.

```
@GraphQLType
@Getter
public class JobInput {

    @GraphQLName("id")
    private long id;

    @GraphQLName("test")
    private String name;

}
```

Unfortunately, when settings the JobInput type, any GraphQL query that is submitted leads to a _NoSuchElementException_ in _MethodDataFetcher#invocationArgs_. The problem seems due to the environment that no longer contains the JobInput argument that is defined with the field. This argument is removed from the environment when _GraphQLAnnotations.ConnectionDataFetcher#get_ is invoked. There is even an explicit comment saying _Exclude arguments_. I am not sure to understand if this removal is a bug (i.e. only arguments related to relay pagination should be removed) or a voluntary action.

Is there a standard way to support arguments with a GraphQLConnection?

**Comment by yrashk** [comment]
Thanks for opening this issue! I will look into this soon and will update you.

**Comment by laurentpellegrino** [comment]
@yrashk Great! Let me know if there is something I can do to help.

**Comment by cnole** [comment]
Any updates? I also ran into this problem. Could you fix this please?

**Comment by CassandraTis** [comment]
up! Thanks!

**Comment by CassandraTis** [comment]
up!

**Comment by CassandraTis** [comment]
@yrashk Are there any updates on this issue? Thank you!

**Comment by guy120494** [comment]
Solved
