### ISSUE TITLE
Documentation about Type Inference is out of date

### ISSUE THREAD

**Issue by sebasjm** [Enigmatis/graphql-java-annotations#34]
Here
https://github.com/graphql-java/graphql-java-annotations#type-inference

Was trying to implement v0.13 and this came out.
Could you please put an example on how this can be achieved with this improvement?

**Comment by yrashk** [comment]
Thanks for pointing this out. Currently, the mechanism for adding types is:

`GraphQLAnnotations.register(typeFunction)`

or (if not using a static version):

`new GraphQLAnnotations().registerType(typeFunction)`

I am a bit overloaded these days — would you mind checking if this works for you and sending a PR for a doc update?
