### ISSUE TITLE
@GraphQLConnection vs @GraphQLDataFetcher

### ISSUE THREAD

**Issue by laurentpellegrino** [Enigmatis/graphql-java-annotations#35]
I have a field which is a List of _chicks_. This last is annotated with _@GraphQLConnection.java_:

```
@GraphQLConnection
@GraphQLDataFetcher(CatDataFetcher.class)
@GraphQLField
public List<Cat> cats;
```

My usecase is to fetch available _cats_ from a database. For this purpose, I have created a _CatDataFetcher_ class that builds and executes a query against my database. It is working but this basic approach fetch all _cats_ in memory before filtering them based on criteria passed with the connection (e.g. _first=10_, _last=3_, etc.). 

Since I have a lot of entries, I would prefer to apply pagination at the database level directly. By default, filtering for a _Connection_ is performed by _SimpleListConnection_ after the execution of a GraphQLDataFetcher. I have seen it is possible to specify a _DispatchingConnection_ with the _@GraphQLConnection_ annotation. 

What would be the recommended way to proceed with my use case? should I move the code that builds the query and execute it in a dedicated _DispatchingConnection_ and simply remove the GraphQLDataFetcher? 

Should _@GraphQLDataFetcher_ never be used when _@GraphQLConnection_ is already set on a field?

In the case I use a custom _DispatchingConnection_ with the _@GraphQLConnection_ annotation, can I assume that additional arguments that will be defined on the field will be accessible from my custom _DispatchingConnection_ (once graphql-java/graphql-java-annotations#33 is fixed)?

**Comment by yrashk** [comment]
Thanks for opening such a detailed issue! I haven't touched that part of the library in a little while and might have forgotten something.

My quick look into it suggests that you might want to subclass your `CatDataFetcher` from connection and pass it in `@GraphQLConnection(connection = CatDataFetcher)` — but again, I haven't had time to verify this.

If you want to discuss this a tad more interactively, feel free to find me on http://gitter.im/graphql-java/graphql-java cht

**Comment by yrashk** [comment]
@lpellegr did you have a chance to try my suggestion?

**Comment by yrashk** [comment]
@lpellegr ping?

**Comment by laurentpellegrino** [comment]
@yrashk Unfortunately, `@GraphQLDataFetcher` expects an instance of `DispatchingConnection` which implies to extend this last and thus creating a constructor that invokes its parent that takes an Object instance, even if it is not needed. Furthermore, this last parameter must be an instance of `List` or `Stream`, otherwise an exception is raised. In my case, I find this design not really convenient. 

Besides, I encountered a few other bugs with this extension. Since, I do not have the time for now to contribute to this project, I have switched to `graphql-java` which is much more verbose but working as expected. I hope to come back to this project soon.

**Comment by guy120494** [comment]
We are working on a solution for this these days.
The solution is a dedicated GraphQLConnnection and a dedicated datafetcher that will be called with the relevant arguments ("first","after",etc.) and will give each entity a custom cursor and will be asked each time if this is the last/first page or not.
I will be happy if you could code review us once we make a PR

**Comment by guy120494** [comment]
#119 fixes the issue
