### ISSUE TITLE
Specify possibleTypes on an interface

### ISSUE THREAD

**Issue by astarz41** [Enigmatis/graphql-java-annotations#38]
Hi, I'm wondering how to set the possible types that implement an interface. Similar to @GraphQLUnion(possibleTypes = TestObject1.class) on Union Types. 

Trying to run an inline fragment query to fetch implementation specific fields, but getting an error like this: "Fragment cannot be spread here as objects of type GraphQLInterfaceType can never be of type GraphQLObjectType"

The query doesn't pass validation, probably because the interface definition has empty "possibleTypes": []

Introspection query result snippet:

        {
          "kind": "INTERFACE",
          "name": "Character",
          "description": null,
          "fields": [.........],
          "inputFields": null,
          "interfaces": null,
          "enumValues": null,
          "possibleTypes": []
        }

I must be missing something.... if anyone has gotten this to work, please let me know!

**Comment by yrashk** [comment]
Anna,

Thanks for opening this issue!

I actually ran into this question myself (as an author of the library), but
then came to conclusion after re-reading specs that if you want
implementation specific details, you gotta use unions. Do you have a
different reading?

**Comment by astarz41** [comment]
Hi Yurii!

Thanks for writing this library, it really does make java graphql code so much cleaner.

Yes, I see this will work with Union types. I'm new to GraphQL, but so far my understanding is interfaces can have some shared and some unique fields, while unions can be completely different.

For interfaces with implementation specific fields, I was going by the description here http://graphql.org/learn/schema/#interfaces The example shows Droid and Human each having unique fields in addition to interface fields. In the query you can use an inline fragment to fetch fields for a specific implementation.

**Comment by yrashk** [comment]
You are right. This needs to be looked into again . Last time I tried to do
this, I failed :) but can't quite remember why

**Comment by micheal-swiggs** [comment]
Any progress and/or workaround with this? I have a similar question here: https://github.com/graphql-java/graphql-java-annotations/issues/100

**Comment by yarinvak** [comment]
You can create an interface type, extend it with classes that have their unique fields, and add it as additionalTypes to the schema.
You should create a typeresolver that determines the possible return types.
