### ISSUE TITLE
Method data fetcher swallowing exceptions

### ISSUE THREAD

**Issue by alexkrebiehl** [Enigmatis/graphql-java-annotations#4]
Hi yrashk,

I'm using your `MethodDataFetcher` to get my data from a service.  My service throws exceptions on failures, but the `MethodDataFetcher` is consuming anything I throw.  The result is I have no data, but `executionResult.getErrors()` is empty.  

Is there a reason that the exceptions are not rethrown?

Thanks,
Alex

**Comment by yrashk** [comment]
Alex,

This definitely sounds like a bug, have not intended this behaviour. From a
quick glance, MethodDataFetcher swallows only a very tiny subset of access
and invocation exceptions. Can you provide a minimal failing test case?

On Thursday, 14 April 2016, Alex Krebiehl notifications@github.com wrote:

> Hi yrashk,
> 
> I'm using your MethodDataFetcher to get my data from a service. My
> service throws exceptions on failures, but the MethodDataFetcher is
> consuming anything I throw. The result is I have no data, but
> executionResult.getErrors() is empty.
> 
> Is there a reason that the exceptions are not rethrown?
> 
> Thanks,
> Alex
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/yrashk/graphql-java-annotations/issues/4

## 

Y.

**Comment by yrashk** [comment]
Actually, nevermind, I found the bug. Will release a fix shortly.

On Thursday, 14 April 2016, Yurii Rashkovskii yrashk@gmail.com wrote:

> Alex,
> 
> This definitely sounds like a bug, have not intended this behaviour. From
> a quick glance, MethodDataFetcher swallows only a very tiny subset of
> access and invocation exceptions. Can you provide a minimal failing test
> case?
> 
> On Thursday, 14 April 2016, Alex Krebiehl <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> 
> > Hi yrashk,
> > 
> > I'm using your MethodDataFetcher to get my data from a service. My
> > service throws exceptions on failures, but the MethodDataFetcher is
> > consuming anything I throw. The result is I have no data, but
> > executionResult.getErrors() is empty.
> > 
> > Is there a reason that the exceptions are not rethrown?
> > 
> > Thanks,
> > Alex
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > https://github.com/yrashk/graphql-java-annotations/issues/4
> 
> ## 
> 
> Y.

## 

Y.

**Comment by yrashk** [comment]
I just released 0.7.1 with this bug fixed. Please note that in order to match graphql-java behaviour and `DataFetcher` interface, the exception your method will be throwing will be re-thrown, but it will be wrapped into a `RuntimeException`

**Comment by yrashk** [comment]
Thanks for reporting!
