### ISSUE TITLE
The GraphQLAnnotations methods throw unecessary exceptions

### ISSUE THREAD

**Issue by bbakerman** [Enigmatis/graphql-java-annotations#40]
The reflection exceptions are re-thrown in the API to create Graph objects

        try {
            GraphQLObjectType IssueFieldQL =  GraphQLAnnotations.object(IssueField.class);
        } catch (IllegalAccessException | NoSuchMethodException | InstantiationException e) {
            throw new RuntimeException(e);
        }

This clutters the usage of the annotations code for no great gain.  Even your own tests use the     @SneakyThrows to get around the annoying nature of this signature.

I suggest it would better to have  GraphQLAnnotationsReflectionException as a runtime exception in the case where consumers provide a bad class

**Comment by yrashk** [comment]
Good point! Can you send a PR?

**Comment by bbakerman** [comment]
Sure...coming up

**Comment by bbakerman** [comment]
PR in place.  Not sure why it didn't reference to this issue.

https://github.com/graphql-java/graphql-java-annotations/pull/42
