### ISSUE TITLE
Consider removing Lombok from implementation

### ISSUE THREAD

**Issue by bbakerman** [Enigmatis/graphql-java-annotations#41]
Could this project consider NOT use Lombok in the implementation of the library 

Good libraries tend to have a limited set of dependencies.  

Lombok is one of the most contentious dependencies out there because of its "magic" nature.

We have an informal ban on it inside my area in Atlassian because of debugging problems at runtime and the byte code weaving side of it at compile time.

I would ask that this otherwise excellent library not use Lombok in its implementation.  I think this will increase its uptake, not just in my company but with others.

I am in the process of creating a PR to see what the impact of removing Lombok would be.

**Comment by yrashk** [comment]
Sure, go ahead! This is a community-driven project, I employ the ideas behind [C4](https://rfc.unprotocols.org/spec:1/C4)

 In a nutshell, this means:

* I merge pull requests rapidly (try!)
* I am open to diverse ideas
* I prefer code now over consensus later

**Comment by yrashk** [comment]
generally, removing lombok is as easy as running delombok on it, https://projectlombok.org/features/delombok.html

On my end, I think it might make sense to tweak these settings:

```
 generated:
    Either 'generate' or 'skip'. generate means: All lombok-generated
    methods, types, and fields get a @Generated("lombok") annotation.
    Default: 'generate'
...
  generateDelombokComment:
    Either 'generate' or 'skip'. generate means: Any file modified by
    delombok will have a comment stating this at the top. Default:
    'generate'
```

**Comment by bbakerman** [comment]
ok - PR coming up

**Comment by jplock** [comment]
@yrashk Would it be possible to deploy a new release of this and update the dependencies graphql-servlet and deploy that as well?  If we could get the rest of @bbakerman's changes merged in, that'd be fantastic!

**Comment by yrashk** [comment]
Sorry I missed this. I'll update releases soon

**Comment by bbakerman** [comment]
Now without lombok
