### ISSUE TITLE
Schema field order is non-deterministic

### ISSUE THREAD

**Issue by nyobe** [Enigmatis/graphql-java-annotations#45]
Hi there,

First, thanks for this wonderful library!

I noticed this while generating schema dumps for Relay.  The ordering of methods and fields returned by Class.getMethods and Class.getFields is [undefined](http://stackoverflow.com/questions/1097807/java-reflection-is-the-order-of-class-fields-and-methods-standardized#1097826), which ends up causing GraphQL Annotations  to generate schemas with arbitrary field orderings.

This unfortunately ends up making schema dumps look like they were modified after each execution. I was wondering if perhaps it would be preferable to sort the methods by name / signature prior to generating graphql fields so that the ordering remains stable. Thoughts?

**Comment by yrashk** [comment]
It's a great idea! Mind contributing a PR?

**Comment by nyobe** [comment]
Sure thing, see #46

**Comment by yrashk** [comment]
Closed via #46
