### ISSUE TITLE
Using observables with method data fetchers

### ISSUE THREAD

**Issue by alexkrebiehl** [Enigmatis/graphql-java-annotations#5]
Is it possible to use observables/futures/etc with method data fetchers?  I have an execution strategy that supports observables, but I'm having trouble wiring it up when I'm returning data from a method.

For example: I have a service that returns an `Observable<Model>`.  I can wire it up using a field builder like so:

``` java
newFieldDefinition().
    .type(Model)
    .dataFetcher(env -> service.getModelById(1234)) // returns an Observable<Model>
    .build()
```

However, if I want to define my field with a MethodDataFetcher, I don't see a clean way to define my return type as `Model`, but really return an `Observable<Model>`:

``` java
// Doesn't work... doesn't know what to do with a return type of observable...?
@GraphQLField
public Observable<Model> getModel(int id) {
    return service.getModelById(1234);
}
```

``` java
// Doesn't work... incompatible return types
@GraphQLField
public Model getModel(int id) {
    return service.getModelById(1234);
}
```

Is this something I can add with a TypeResolver?  (i.e., if the return type is `Observable<T>`, then the return type should map to `T`).  Or does it have to be baked into the library?  As always, thanks for your time.

Alex

**Comment by yrashk** [comment]
Alex,

I suggest doing the following:

Implement a `TypeFunction` for `Observable<T>` similarly to `Optional<T>` implementation https://github.com/yrashk/graphql-java-annotations/blob/master/src/main/java/graphql/annotations/DefaultTypeFunction.java#L99-L117

You can register it by doing `DefaultTypeFunction.instance.register(Observable.class, new ObservableFunction())`

Then implement its handling in your execution strategy (which I suggest should extend `EnhancedExecutionStrategy` from this library as it bakes `Optional` support in) similar to this https://github.com/yrashk/graphql-java-annotations/blob/master/src/main/java/graphql/annotations/EnhancedExecutionStrategy.java#L30-L34

Does this help?

**Comment by alexkrebiehl** [comment]
Excellent.  That was very helpful.  Thanks!
