### ISSUE TITLE
Inject bean into DataFetcher of GraphQL failed

### ISSUE THREAD

**Issue by shishuwu** [Enigmatis/graphql-java-annotations#50]
I'm using **Spring** & graphql-java (graphql-java-annotation) in my project. For retrieving data part, i'm using a **DataFetcher** to get data from a service **bean** (from database).

The weird thing is that: myService is always null.

More detailed information, please refer to my [question and the workaround](http://stackoverflow.com/questions/41440026/inject-bean-into-datafetcher-of-graphql) on stackoverflow.

**Comment by bbakerman** [comment]
The library is agnostic about what injection framework is used.  Some maybe using Spring - others may be using Guice / PICO / whatever.

The work around listed works for Spring people but it should not be part of the library per se, unless the library wants to become Spring specific
