### ISSUE TITLE
Argument must be annotated with @GraphQLName, otherwise it would fail

### ISSUE THREAD

**Issue by shishuwu** [Enigmatis/graphql-java-annotations#51]
If i don't add `@GraphQLName("name") `, then method would not be recognized correctly! (version: 0.13.2)

    @GraphQLField
    @GraphQLDataFetcher(MyDataFetcher.class)
    public String findByName(@GraphQLName("name") String name){
        return null;
    }

**Comment by yrashk** [comment]
Do you use `-parameters` javac option?

**Comment by shishuwu** [comment]
@yrashk Really appreciate, it works. 
(BTW, maybe you should update it in the document :) )

**Comment by yrashk** [comment]
I agree. Can you send a PR?
