### ISSUE TITLE
Specifying a data fetcher for a mutation does not get called during execution

### ISSUE THREAD

**Issue by jamhall** [Enigmatis/graphql-java-annotations#56]
Hello,

Thanks for your great work!  Using this library has definitely made working with GraphQL in Java a pleasure.

I have the following mutation:

```java
    @GraphQLField
    @GraphQLName("createPart")
    @GraphQLRelayMutation
    @GraphQLDataFetcher(CreatePartDataFetcher.class)
    public static CreatePartPayload createPart(@GraphQLName("name")
                                               @GraphQLNonNull String name,
                                               @GraphQLName("description")
                                               @GraphQLNonNull String description) {
        return null;
    }
```

I have the following data fetcher:

```java
@Service
@Log4j2
public class CreatePartDataFetcher extends BaseDataFetcher {
    @Override
    public CreatePartPayload get(final DataFetchingEnvironment environment) {
        log.debug("Creating part");
        final Object input = environment.getArgument("input");
        final Part part = mapper.map(input, Part.class);
        final PartService partService = applicationContext.getBean(PartService.class);
        partService.save(part);
        return new CreatePartPayload(mapper.map(part, PartType.class));
    }
}
```

The data fetcher is not called....

I have used the same implementation for queries and the data fetcher is successfully called. What am I doing wrong?

EDIT: It would be nice to have an annotation called @GraphQLDataIngester  for this purpose.
EDIT: Looking at this [code](https://github.com/graphql-java/graphql-java-annotations/blob/812fd600788a9c0f1d4418ff557ad8b8ca92147f/src/main/java/graphql/annotations/GraphQLAnnotations.java#L515) it appears it is not possible to specify a custom data fetcher. :( I use spring, so I can't inject a service into the type as normally would. I have to use this data fetcher work around to get access to the spring environment:

```java
public abstract class BaseDataFetcher implements DataFetcher, ApplicationContextAware {

    protected static Mapper mapper = new DozerBeanMapper();
    protected static ApplicationContext applicationContext;

    @Override
    public void setApplicationContext(final ApplicationContext context) {
        applicationContext = context;
    }
}
```

**Comment by yarinvak** [comment]
seems to work by implementing DataFetcher at the current version. Im closing this issue because its very old and I wasnt able to simulate this. If this issue is still relevant, open a new one please

**Comment by dearshor** [comment]
I'm using 
```xml
                <dependency>
			<groupId>com.graphql-java</groupId>
			<artifactId>graphiql-spring-boot-starter</artifactId>
			<version>3.9.2</version>
		</dependency>

                <dependency>
			<groupId>com.graphql-java</groupId>
			<artifactId>graphql-java-servlet</artifactId>
			<version>4.7.0</version>
		</dependency>

               <dependency>
		        <groupId>com.graphql-java</groupId>
			<artifactId>graphql-java</artifactId>
			<version>6.0</version>
			<scope>compile</scope>
		</dependency>
```
and this issue is still relevant. as  @jamhall said , 

> Looking at this [code](https://github.com/graphql-java/graphql-java-annotations/blob/812fd600788a9c0f1d4418ff557ad8b8ca92147f/src/main/java/graphql/annotations/GraphQLAnnotations.java#L515) it appears it is not possible to specify a custom data fetcher. :( I use spring, so I can't inject a service into the type as normally would. I have to use this data fetcher work around to get access to the spring environment

I'm using spring too, so what should I do to workaround? Thanks.
