### ISSUE TITLE
Query with fragment fails

### ISSUE THREAD

**Issue by mattesja** [Enigmatis/graphql-java-annotations#62]
A graphql query which uses fragments fails:
Example:  `({items { ... on MyObject {a, my {b}} ... on MyObject2 {a, b}  }}`

The return type of getItems is an interface.
MyObject and MyObject2 are two different implementations of that interface.

I've created two demo classes (plain, annotations) which demonstrates the problem:
https://github.com/mattesja/graphql-helloworld

HelloWorldPlain.java shows how the fragment query works in plain graphql-java.
HelloWorldAnnotation.java shows how the fragment query fails with graphql-java-annotations.

**Hints**

- I discovered, that the GraphQLInterfaceType objects are instantiated multiple times. I guess this is the cause, that makes PossibleFragmentSpreads.doTypesOverlap() fail.
- The GraphQLInterfaceType is not found in the schema dictionary:
   Class: PossibleFragmentSpreads.doTypesOverlap() 
   Line: new SchemaUtil().findImplementations(getValidationContext().getSchema(), (GraphQLInterfaceType) parent);

**Comment by mattesja** [comment]
I have created a pull request for this issue:
https://github.com/graphql-java/graphql-java-annotations/pull/64

Sorry :( I've forgotten to put the issue id in the commit comment.

If you won't accept it, I would like to here your comments :-)

**Comment by guy120494** [comment]
Can this be closed?
