### ISSUE TITLE
GraphQLConnection not preserved on both sides of mutually recursive associations

### ISSUE THREAD

**Issue by tjoneseng** [Enigmatis/graphql-java-annotations#63]
I have a simple schema with two object types: Task, and User.  A Task references a list of Users and a User references a list of Tasks.  Both these associations are marked with @GraphQLConnection.  When the schema is built at runtime, only one of these ends up as a connection, and the other ends up as a GraphQLList.

When I construct the schema manually (not using annotations) with GraphQLTypeReference as both edge types, the result is correct.

I've attached a simple test case and my schema code as an example.

[Archive.zip](https://github.com/graphql-java/graphql-java-annotations/files/775575/Archive.zip)

**Comment by yarinvak** [comment]
seems to work, but you might want to check again
