### ISSUE TITLE
The underlying TypeFunction is not available to registered extension TypeFunctions

### ISSUE THREAD

**Issue by bbakerman** [Enigmatis/graphql-java-annotations#68]
Lets say I want to write an extension "container" TypeFunction

Imagine its like the build in List one where it detects the "outer type" and then wants to recurse into the inner types and run them back thought the default type processor again.

For example this is the current List type function

            @Override
        public GraphQLType apply(Class<?> aClass, AnnotatedType annotatedType) {
            if (!(annotatedType instanceof AnnotatedParameterizedType)) {
                throw new IllegalArgumentException("List type parameter should be specified");
            }
            AnnotatedParameterizedType parameterizedType = (AnnotatedParameterizedType) annotatedType;
            AnnotatedType arg = parameterizedType.getAnnotatedActualTypeArguments()[0];
            Class<?> klass;
            if (arg.getType() instanceof ParameterizedType) {
                klass = (Class<?>) ((ParameterizedType) (arg.getType())).getRawType();
            } else {
                klass = (Class<?>) arg.getType();
            }
            return new GraphQLList(DefaultTypeFunction.this.apply(klass, arg));
        }

Notice how after unwrapping the "container" it can call back into sub types via

    DefaultTypeFunction.this.apply(klass, arg)

How if you write your own TypeFunction you cant get a hold of the default TypeFunction

 Its defined as

        protected TypeFunction defaultTypeFunction;

So you can make a sub class and hence extract it out but I think it should be public and hence available for re-use for "container" types.

**Comment by Fgerthoffert** [comment]
Hi @bbakerman,

We're helping with project maintenance and reviewing the list of opened PRs and Issues.

This issue was created quite a while ago, we were wondering if you were still interested in the outcome, please let us know if this is the case.

Without an answer by July 1st, 2023, this issue will be closed as "inactive" (and can always be re-opened later on if needed).

Thanks,
