### ISSUE TITLE
How to get JSON from ExecutionResult?

### ISSUE THREAD

**Issue by graphan** [Enigmatis/graphql-java-annotations#69]
Hi All,

Thank you for this project. It looks promising. I am trying to launch an [exemplary spring boot jpa application](http://javabeat.net/spring-data-jpa/) and add graphql-java-annotations to it. If someone knows how to connect them in a simple way, I would be grateful for an example.

Meanwhile, when I was tinkering with the project I noticed that ExecutionResult returns something like:
{defaultUser={name=Test Name}}

It is taken from your tests. Could you tell me why it is not like JSON? What I should do to receive JSON as a result?

**Comment by bbakerman** [comment]
The graphql does not define JSON as being the reponse per se.

http://facebook.github.io/graphql/#sec-Response

It only defines that the object passed back should have a certain shape.

The ExecutionResult is that shape.

You can then use Jersey / Spring-REST / Jackson / gSON / whatever to create JSON representations from this object

**Comment by xetra11** [comment]
@bbakerman 
Can you give an example how to format this as JSON with the mentioned frameworks? Like Spring-REST?
