### ISSUE TITLE
Release 0.13.2 to maven central

### ISSUE THREAD

**Issue by chonton-elementum** [Enigmatis/graphql-java-annotations#70]
or is it 0.13.3 or 0.14.0?

**Comment by athlordJojo** [comment]
i am a bit confused... what is the most recent version of this project ? 0.13.1 as the readme said is it not ? in the repo i cant find a branch 0.13.2 or 0.14.0 ...

**Comment by ageroe** [comment]
When can we expect the next release? PR #64 of mattesja fixes my problem with interfaces and is already merged and waits to be released :)

**Comment by apottere** [comment]
Just waiting for JFrog to include my graphql-java-annotations repo in JCenter, then I'll be able to publish `0.14.0` to maven central: https://bintray.com/apottere/maven/graphql-java-annotations/0.14.0

**Comment by apottere** [comment]
Version `0.14.0` is released.
