### ISSUE TITLE
GraphQL ID support ?

### ISSUE THREAD

**Issue by joel-costigliola** [Enigmatis/graphql-java-annotations#71]
It might be a dumb question but it is not clear to me whether `GraphQLID` is supported or not.
I see it defined in graphql-java [here](https://github.com/graphql-java/graphql-java/blob/ec399372416d560ac3b122d3a60f722366c5df2b/src/main/java/graphql/Scalars.java#L315) I'm not sure how it use since I use only annotations ;-)

Does it make sense to have a `GraphQLID` annotation ? Something that I could use it like:
```java
public class LogBatch {

	private final String id;

	public LogBatch(final String id) {
		this.id = id;
	}

	@GraphQLID
	public String getId() {
		return this.id;
	}

}
```

**Comment by guy120494** [comment]
Fixed
