### ISSUE TITLE
How to define an argument in the schema ? 

### ISSUE THREAD

**Issue by athlordJojo** [Enigmatis/graphql-java-annotations#76]
I cant find any example how i can add an argument with graphql-annotations? 
can anybody help ?

**Comment by athlordJojo** [comment]
So for all the others, here my solution:

    @GraphQLField
    @GraphQLName("files")
    @GraphQLDescription("A description")
    @GraphQLInvokeDetached
    @GraphQLDataFetcher(value = VideoDataFetcher.class)
    public List<Video> files(@GraphQLName("orderBy") @GraphQLDescription("The order how the files are sorted") Order order, @GraphQLName("orderOn") FilesOrderProperty orderOn) PublicationState publicationState) {
        return new ArrayList<>();
    }

**Comment by bbakerman** [comment]
The readme outlines 2 ways.  You can have a data fetcher annotated in via `@GraphQLDataFetcher` or you can have a method that takes parameters

    public String field(@GraphQLName("val") String value) {
     return value;
   }

In the example above you have done both
