### ISSUE TITLE
IncompatibleClassChangeError thrown during data fetching if used with graphql-java 2.4.0

### ISSUE THREAD

**Issue by vojtechmasa** [Enigmatis/graphql-java-annotations#77]
When used with graphql-java 2.4.0
java.lang.IncompatibleClassChangeError: Found interface graphql.schema.DataFetchingEnvironment is thrown during data fetching.
DataFetchingEnvironmnet has been changed from a class to an interface in graphql-java 2.4.0.

**Comment by danielocampo2** [comment]
Also there are some other issues if you don't annotate with GraphQLName. It'd be cool to have the library updated to 2.4.0.
I started doing that in a branch and fixed some of the issues but there's more fixes that need to be done and I don't have a big knowledge of the internals of the library honestly... Will see if at some point I can finish and make a PR with this update.

**Comment by danielocampo2** [comment]
This issue should be fixed now with the integration of 3.0.0

**Comment by guy120494** [comment]
Now that we have graphql-java 3.0.0, I close this issue
