### ISSUE TITLE
New version release?

### ISSUE THREAD

**Issue by danielocampo2** [Enigmatis/graphql-java-annotations#79]
Hi, first I wanna thank you all for the library, it's quite cool and makes working with GraphQL a way better experience.
I've noticed that though there was quite a decent amount of activity and commits during the last months, the last version is from Nov 2016. Is there any reason you didn't decide to release a new version just yet?
I am particularly interested in latest changes that add args to the DataFetcher annotation. And though I could potentially use latest commits in order to gain that support, given our current configuration could be kind of a hassle (and maybe even impossible to not be attached to a release - which kind of makes sense sometimes - )

Thanks!

**Comment by danielocampo2** [comment]
Actually I just noticed this same discussion on Issue #70 and does not seem to have a lot of track. What are the possibilities of 0.13.2 being released soon? What it depends on?

**Comment by danielocampo2** [comment]
@apottere Hey, I saw you released a new version. Thanks a lot for that. Do you know when is it going to be available through Maven Central?

Thanks!

**Comment by apottere** [comment]
I commented on the other issue, I was waiting for jfrog.  They just
approved my request, so I'll sync it tomorrow morning (est).

**Comment by apottere** [comment]
Version `0.14.0` is released.
