### ISSUE TITLE
The future with GraphQL 3.0.0

### ISSUE THREAD

**Issue by guy120494** [Enigmatis/graphql-java-annotations#84]
I would like to know what are the plans for this library, now that graphql java 3.0.0 is out and we can do a schema first programming. As I already use this library at work (and it would pretty hard to switch to schema first now) it would be grate if the library keeps to be supported. (I would be happy to PR to make this library depends on graphql java 3.0.0)

So what is the future of this library?
Thanks!

**Comment by danielocampo2** [comment]
I think that would be great. I asked a similar question (though I didn't go too far and asked at least about 2.4.0) in #83.
Most likely 3.0.0 will be more difficult to integrate as it has breaking changes, but it is definitely something we need.

As I can see for the last weeks, this repo does not seem to be maintained too much and it looks as it will really depend on new members of the community that might want to help or even take ownership of it. 
graphql-java community seems pretty active but for some reason this repo is a bit behind though in my opinion it offers something truly useful.

**Comment by bbakerman** [comment]
PR up to get this library to graphql-java 3.x
