### ISSUE TITLE
Type coersion annotation request

### ISSUE THREAD

**Issue by NonLogicalDev** [Enigmatis/graphql-java-annotations#98]
It seems like a fairly useful operation is currently impossible to implement with annotations.
Say I have a class:

```
class Model {
  @GraphQLField
  public String name() {
     return "Hello";
  }

  @GraphQLField
  public DateTime date() {
     return DateTime.now();
  }
}
```

The DateTime class is not supported by GraphQL, but I would want to be able to serialize it still. It would be nice to be able to substitute the type to a type that is compatible with GraphQL. Example:

```
class GQLDate {
  @GraphQLField
  public String value;

  public GQLDate(DateTime date) {
     this.value = date.toString()
  }
}

class Model {
  @GraphQLField
  public String name() {
     return "Hello";
  }

  @GraphQLField
  @GraphQLTypeCoerse(GQLDate.class)
  public DateTime date() {
     return DateTime.now()
  }
}
```

**Comment by guy120494** [comment]
Hi @NonLogicalDev. Did you read the Type Inference in the readme? Maybe you can solve your problem by register the DateTime as a type?

**Comment by yarinvak** [comment]
hey, I believe guy answered your question :)
